[package]
name = "chord3"
version = "0.2.0"
authors = ["Rasmus Kaj <kaj@kth.se>"]
repository = "https://github.com/kaj/chord3"
description = "Create pdf songbooks from chopro source."

[dependencies]
regex = "*"
lazy_static = "*"
clap = "*"

[dependencies.pdf]
git = "https://github.com/kaj/rust-pdf.git"
