[package]
name = "chord3"
version = "0.3.0"
authors = ["Rasmus Kaj <kaj@kth.se>"]
repository = "https://github.com/kaj/chord3"
description = "Create pdf songbooks from chopro source."
license = "Beerware"

[dependencies]
clap = "^2"
lazy_static = "^0.2"
pdf = "^0.5"
regex = "^0.1"
